# Generated by Django 4.2.7 on 2023-11-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(choices=[('A', '15 Minutes'), ('B', '30 Minutes'), ('C', '45 Minutes'), ('D', '1 Hour'), ('E', '1.5 Hours'), ('F', '2 Hours'), ('G', 'More than 2 Hours')], default='A', max_length=50),
        ),
    ]
