# Generated by Django 4.2.7 on 2023-11-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
