# Generated by Django 4.2.7 on 2023-11-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_workout_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('weightlifting', 'Weightlifting'), ('flexibility', 'Flexibility'), ('HIIT', 'High-Intensity Interval Training'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('walking', 'Walking'), ('other', 'Other')], default='cardio', max_length=20),
        ),
    ]
